name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'applications/dotnet/**'

# on:

#   push:
#     branches: [ "main" ]

#   pull_request:
#     branches: [ "main" ]
#   paths:
#     - 'applications/dotnet/**'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    permissions: read-all
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install SonarQube scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: List all the files under the directory
        shell: powershell
        run: |
          dir

      - name: Build and analyze
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"GithubActions" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          dotnet build .\applications/dotnet/SampleApp.sln
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"